set nocompatible

filetype off
call pathogen#helptags()
call pathogen#runtime_append_all_bundles()
filetype plugin indent on

set modelines=0

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

set encoding=utf-8
set scrolloff=3
set autoindent
set showmode
set showcmd
set hidden
set wildmenu
set wildmode=list:longest
set visualbell
set cursorline
set ttyfast
set ruler
set backspace=indent,eol,start
set laststatus=2

set ignorecase
set smartcase
set incsearch
set showmatch
set hlsearch
nnoremap <leader><space> :noh<cr>

set wrap
set textwidth=85
set formatoptions=qrn1

nnoremap j gj
nnoremap k gk

set relativenumber

set nobackup
set noswapfile

" gui options
set guioptions-=T
colorscheme mustang
syntax on
" set lines=45 columns=130

" gg configurations
:map <F2> :nohl<CR>
:map <F3> :set wrap! <CR>
